apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: rollouts-demo
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rollouts-demo
  progressDeadlineSeconds: 60
  service:
    port: 8080
    gateways:
      - default/rollouts-demo-gateway
    hosts:
      - "*"
  analysis:
    interval: 1m
    threshold: 5
    iterations: 2
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        # maximum req duration P99
        # milliseconds
        thresholdRange:
          max: 100000
        interval: 1m
    match:
      - headers:
          user-agent:
            regex: ".*CloudNativeDays.*"
    webhooks:
      - name: load-test
        url: http://flagger-loadtester/
        timeout: 2s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://rollouts-demo-canary.default:8080/"
      - name: "promotion gate"
        type: confirm-promotion
        url: http://flagger-loadtester/gate/check
      - name: "rollback gate"
        type: rollback
        url: http://flagger-loadtester/rollback/check
