apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: rollouts-demo
  namespace: default
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rollouts-demo
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  service:
    # service port number
    port: 8080
    # Istio gateways (optional)
    gateways:
      - default/rollouts-demo-gateway
    hosts:
      - "*"
  analysis:
    # schedule interval (default 60s)
    interval: 1m
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 100
    stepWeight: 20
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 1000
        interval: 1m
    webhooks:
      - name: load-test
        url: http://flagger-loadtester/
        timeout: 2s
        type: pre-rollout
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://rollouts-demo-canary.default:8080/"
      - name: load-test
        url: http://flagger-loadtester/
        timeout: 2s
        type: rollout
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://rollouts-demo-canary.default:8080/"
